#!/bin/bash

# GIT_BRANCH=<GIT_BRANCH_NAME> :: should be the real git branch that in this repository will be deployed.
# By now there is the limitation: $GIT_BRANCH should be a valid env (with conf files .*.<ENV>)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/mount_etna.sh > /dev/null
set_vars "" "" "" "" > /dev/null

while read oldrev newrev ref
do
    if [[ "$FORGE_DEBUG" == "1" ]];
    then
        echo "[DEBUG] FORGE_DRY_RUN..: $FORGE_DRY_RUN :: original SCRIPT_DIR....: ${SCRIPT_DIR}"
        echo "[DEBUG] TARGET_ENV.....: ${TARGET_ENV}  :: GIT_BRANCH.............: $GIT_BRANCH   :: DEFAULT_TARGET_ENV..: $DEFAULT_TARGET_ENV :: Using DEPLOYMENT_FILE..: ${DEPLOYMENT_FILE}"
        echo "[DEBUG] ref............: $ref           :: oldrev.........: $oldrev               :: newrev..: $newrev"
    fi

    if [ "$newrev" = "0000000000000000000000000000000000000000" ]; then
        continue
    fi

    if [ "$ref" = "refs/heads/$TARGET_ENV" ] || [ "$ref" = "refs/triggers/deploy" ];
    then
        if [[ "$FORGE_DRY_RUN" == "1" ]];
        then
            echo "[DRY_RUN] FORGE_DRY_RUN..: $FORGE_DRY_RUN :: original SCRIPT_DIR....: ${SCRIPT_DIR}"
            echo "[DRY_RUN] TARGET_ENV.....: ${TARGET_ENV}  :: Using DEPLOYMENT_FILE..: ${DEPLOYMENT_FILE}"
            echo "-------------------------------------------"

            exit 0
        fi
        echo "[EXEC-DEPLOY] Ref '${ref}' received along with oldrev '${oldrev}' and newrev '${newrev}'. Deploying branch '${GIT_BRANCH}' to env '${TARGET_ENV}'..."
        deploy
    else
        echo "[NO-DEPLOY] Ref '${ref}' received along with oldrev '${oldrev}' and newrev '${newrev}'. Doing nothing: only the '${GIT_BRANCH}' (expecting $TARGET_ENV) branch may be deployed on this server."
    fi
done
