# TODO implement dynamic user and group
/var/log/river/is-mounted.log {
	hourly
	missingok
	rotate 24
	compress 
	create 0640 ladm adm
    notifempty

	# sharedscripts
	# postrotate
	# 	systemctl reload your-app
	# endscript
}